
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
from scores import center_window


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\WorkProjects\clothes\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_sizes():
    if (entry_1.get() == "" or
        entry_2.get() == ""):
        messagebox.showwarning("خطا", "عذراً، املأ جميع الفراغات")
        return
    file_to_run_path = r"D:\WorkProjects\clothes\sizes.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)

def open_register():
    file_to_run_path = r"D:\WorkProjects\clothes\register.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)


window = Tk()
window.title('Project')

window.geometry("396x688")
window.configure(bg = "#EBD7D7")


canvas = Canvas(
    window,
    bg = "#EBD7D7",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    201.0,
    458.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_sizes,
    relief="flat"
)
button_1.place(
    x=27.0,
    y=620.0,
    width=121.0,
    height=47.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_register,
    relief="flat"
)
button_2.place(
    x=63.0,
    y=535.0,
    width=132.0,
    height=26.0
)

canvas.create_text(
    210.0,
    537.0,
    anchor="nw",
    text="ليس لديك حساب؟",
    fill="#000000",
    font=("Inter", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    211.0,
    484.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EFDAD9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=86.5,
    y=457.0,
    width=249.0,
    height=53.0
)

canvas.create_text(
    240.0,
    408.0,
    anchor="nw",
    text="الرقم السري",
    fill="#83787A",
    font=("Inter", 27 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    211.0,
    362.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EFD9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=86.5,
    y=335.0,
    width=249.0,
    height=53.0
)

canvas.create_text(
    240.0,
    288.0,
    anchor="nw",
    text="إسم المستخدم",
    fill="#83787A",
    font=("Inter", 27 * -1)
)

canvas.create_text(
    140.0,
    209.0,
    anchor="nw",
    text="تسجيل دخول ",
    fill="#DDB5B5",
    font=("Inter", 35 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    201.0,
    93.0,
    image=image_image_2
)
window.resizable(False, False)
center_window(window)
window.mainloop()
