
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from center import center_window


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\WorkProjects\clothes\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_page():
    file_to_run_path = r"D:\WorkProjects\clothes\login.py"
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)

window = Tk()
window.title('Project')

window.geometry("396x688")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    197.0,
    536.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_page,
    relief="flat"
)
button_1.place(
    x=42.0,
    y=633.0,
    width=100.0,
    height=43.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    221.0,
    277.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    160.0,
    116.0,
    image=image_image_3
)

canvas.create_text(
    140.0,
    20.0,
    anchor="nw",
    text="الجسم المستطيل",
    fill="#DDB5B5",
    font=("Inter", 26 * -1)
)
window.resizable(False, False)
center_window(window)
window.mainloop()
