
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
from center import center_window


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\WorkProjects\BodyStyleAR\assets\frame2") # مسار الفريم


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_sizes():
    # نتأكد ان جميع الحقول غير فارغة
    if (entry_1.get() == "" or
        entry_2.get() == "" or
        entry_3.get() == ""):
        messagebox.showwarning("خطأ", "عذراً، املأ جميع الحقول")
        return
    file_to_run_path = r"D:\WorkProjects\BodyStyleAR\sizes.py" #مسار صفحة القياسات
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)

def open_login():
    file_to_run_path = r"D:\WorkProjects\BodyStyleAR\login.py" # مسار صفحة تسجيل الدخول
    window.destroy()
    subprocess.run(["python", file_to_run_path], check=True)

window = Tk()
window.title('Project') #عنوان الصفحة

window.geometry("396x688")
window.configure(bg = "#EBD7D7")


canvas = Canvas(
    window,
    bg = "#EBD7D7",
    height = 688,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    201.0,
    458.0,
    image=image_image_1
)
# زر التالي
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_sizes,
    relief="flat"
)
button_1.place(
    x=27.0,
    y=620.0,
    width=121.0,
    height=47.0
)
# زر تسجيل الدخول
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=open_login,
    relief="flat"
)
button_2.place(
    x=94.0,
    y=565.0,
    width=108.0,
    height=26.0
)

canvas.create_text(
    210.0,
    570.0,
    anchor="nw",
    text="لديك حساب؟",
    fill="#000000",
    font=("Inter", 20 * -1)
)
#حقل الرقم السري
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    215.0,
    520.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EFDAD9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=90.5,
    y=493.0,
    width=249.0,
    height=53.0
)

canvas.create_text(
    240.0,
    457.0,
    anchor="nw",
    text="الرقم السري",
    fill="#83787A",
    font=("Inter", 27 * -1)
)
#حقل البريد الالكتروني
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    221.0,
    416.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EFDAD9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=96.5,
    y=389.0,
    width=249.0,
    height=53.0
)

canvas.create_text(
    200.0,
    355.0,
    anchor="nw",
    text="البريد الإلكتروني",
    fill="#83787A",
    font=("Inter", 27 * -1)
)
#حقل الرقم السري
entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    215.0,
    315.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#EFD9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=90.5,
    y=288.0,
    width=249.0,
    height=53.0
)

canvas.create_text(
    235.0,
    250.0,
    anchor="nw",
    text="إسم المستخدم",
    fill="#83787A",
    font=("Inter", 27 * -1)
)

canvas.create_text(
    92.0,
    180.0,
    anchor="nw",
    text="تسجيل مستخدم جديد ",
    fill="#DDB5B5",
    font=("Inter", 35 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    201.0,
    93.0,
    image=image_image_2
)
window.resizable(False, False)
center_window(window)
window.mainloop()
